In [17]:
from array import array
my_array = array('i', [1,2,3,4,5])

In [18]:
my_array

array('i', [1, 2, 3, 4, 5])

### NumPy Array (Powerful Numerical Arrays)

In [19]:
import numpy as np
arr = np.array([1,2,3,4])

In [20]:
arr

array([1, 2, 3, 4])

In [21]:
type(arr)

numpy.ndarray

In [22]:
arr.ndim

1

In [23]:
arr.dtype

dtype('int32')

In [24]:
import numpy as np
array_new = np.array([1,2,3,4,5,6])

In [33]:
array_new + 3

array([4, 5, 6, 7, 8, 9])

In [34]:
type(array_new)

numpy.ndarray

### Using NumPy As np

In [37]:
# Example1
import numpy as np
my_numpy_array = np.array([1,2,3,4,5])

In [40]:
new_arr = my_numpy_array * 3

In [41]:
new_arr

array([ 3,  6,  9, 12, 15])

In [42]:
type(my_numpy_array)

numpy.ndarray

In [45]:
# Example2 
import numpy as np

my_array = np.array([1,2,3,])
result = my_array * 2
print(result)

[2 4 6]


In [46]:
arr

array([1, 2, 3, 4])

In [50]:
arr  > 2

array([False, False,  True,  True])

In [51]:
# Example3 
my_array = np.array([1,2,3,])
result = my_array * 3
print(result)

[3 6 9]


### Matrix

In [54]:
arr_2d = np.array([[0,1,2,3],[4,5,6,7],[8,9,0,5]])

In [55]:
arr_2d

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 9, 0, 5]])

In [62]:
arr_2d * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18,  0, 10]])

In [63]:
arr_2d + 3

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12,  3,  8]])

In [64]:
arr_2d - 2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7, -2,  3]])

## Read a CSV file 

In [72]:
import pandas as pd
data = pd.read_csv(r"C:\Users\DELL\Desktop\tit (1).csv")

In [73]:
data.head()

Unnamed: 0  survived  pclass     sex   age  sibsp  parch     fare embarked  \
0           0         0       3    male  22.0      1      0   7.2500        S   
1           1         1       1  female  38.0      1      0  71.2833        C   
2           2         1       3  female  26.0      0      0   7.9250        S   
3           3         1       1  female  35.0      1      0  53.1000        S   
4           4         0       3    male  35.0      0      0   8.0500        S   

   class    who  adult_male deck  embark_town alive  alone  
0  Third    man        True  NaN  Southampton    no  False  
1  First  woman       False    C    Cherbourg   yes  False  
2  Third  woman       False  NaN  Southampton   yes   True  
3  First  woman       False    C  Southampton   yes  False  
4  Third    man        True  NaN  Southampton    no   True

In [75]:
data.shape

(891, 16)

In [76]:
import numpy as np
list_data = [1,2,3,4,5]
array_from_list = np.array(list_data)

In [77]:
list_data

[1, 2, 3, 4, 5]

In [78]:
type(list_data)

list

In [79]:
list_data

[1, 2, 3, 4, 5]

In [80]:
array_from_list

array([1, 2, 3, 4, 5])

In [81]:
type(array_from_list)

numpy.ndarray